// Generated by CoffeeScript 1.6.3
var j3r;

j3r = {};

j3r.App = (function() {
  function App() {
    this.elements = {
      header: $('#header-wrapper'),
      info: $('#info-wrapper'),
      content: $('#content-wrapper'),
      footer: $('#footer-wrapper')
    };
    this.user = new j3r.User(io.connect(), this.elements);
    return;
  }

  App.prototype.logInUser = function(mail) {
    this.user.logIn(mail);
  };

  return App;

})();

j3r.changeContent = function(parentEl, content) {
  return parentEl.empty().append(content);
};
