// Generated by CoffeeScript 1.6.3
j3r.Us = (function() {
  function Us() {}

  construct(function(io, elements, data) {
    var itemData, _results;
    this.io = io;
    this.elements = elements;
    this.data = {};
    _results = [];
    for (itemData in data) {
      _results.push(this.data[itemData.id] = {
        title: itemData.title,
        description: itemData.description
      });
    }
    return _results;
  });

  Us.prototype.getUsList = function(data) {
    var id, itemData, liEl, ulEl, usEl, _ref;
    usEl = $('<div id="list-choose-us"></div>');
    if (this.data.length > 0) {
      ulEl = $('<ul></ul>');
      _ref = this.data;
      for (id in _ref) {
        itemData = _ref[id];
        liEl = $('<li></li>');
        liEl.append(this.getUsItem(id, itemData));
        ulEl.append(liEl);
      }
      usEl.append(ulEl);
    } else {
      usEl.append($('<div id="msg-info">no work. go and fuck yourself</div>'));
    }
    return usEl;
  };

  Us.prototype.getUsItem = function(itemData) {
    var usItem;
    return usItem = $('<div class="us-item" data-us-item-id="' + id + '"><span class="us-item-title">\
          ' + itemData.title + '</span><br>' + itemData.description + '</div>');
  };

  Us.prototype.startVoting = function(id) {
    var confirmBtn, inputConfirm, wrapper;
    this.io.emit('user_story_for_estimation', {
      id: this.item.id
    });
    wrapper = $('<div id="voting-header"></div>');
    wrapper.append(this.item.getUsItem(id, this.data[id]));
    inputConfirm = $('<input id="voting-input">');
    confirmBtn = $('<button id="voting-confirm">Confirm voting</button>');
    wrapper.append(inputConfirm);
    wrapper.append(confirmBtn);
    confirmBtn.on('click', function() {
      if (inputConfirm.val() !== '') {
        return this.io.emit('user_story_estimation_end', {
          estimation: inputConfirm.val()
        });
      } else {
        return console.log('cislo vole');
      }
    });
    wrapper.apend($('<div id="voting-info"></div>'));
    j3r.changeContent(this.elements.content, wrapper);
  };

  Us.prototype.addVote = function(data) {
    var voteInfo;
    voteInfo = $('<div class="vote-info">' + data.user + ': <strong>' + id.value + '</strong></div>');
    this.elements.content.append(voteInfo);
  };

  return Us;

})();
