// Generated by CoffeeScript 1.6.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

j3r.Us = (function() {
  function Us(io, elements, data) {
    var item, _i, _len;
    this.io = io;
    this.elements = elements;
    this.startVoting = __bind(this.startVoting, this);
    this.hasUs = data.length > 0 ? true : false;
    this.data = {};
    for (_i = 0, _len = data.length; _i < _len; _i++) {
      item = data[_i];
      this.data[item.id] = item;
    }
    return;
  }

  Us.prototype.getUsList = function() {
    var id, itemData, liEl, ulEl, usEl, _ref;
    usEl = $('<div id="list-choose-us" class="component"></div>');
    if (this.hasUs) {
      ulEl = $('<ul></ul>');
      _ref = this.data;
      for (id in _ref) {
        itemData = _ref[id];
        liEl = $('<li></li>');
        liEl.append(this.getUsItem(itemData));
        ulEl.append(liEl);
      }
      usEl.append(ulEl);
    } else {
      usEl.append($('<div class="msg-info component">no work. go and fuck yourself</div>'));
    }
    return usEl;
  };

  Us.prototype.getUsItem = function(itemData) {
    var usItem;
    return usItem = $((itemData.description != null) + '</div>' ? '<div class="us-item" data-us-item-id="' + itemData.id + '"><span class="us-item-title">\
          ' + itemData.title + '</span><br>' + itemData.description : void 0);
  };

  Us.prototype.startVoting = function(id) {
    var confirmBtn, inputConfirm, votingInfoWrapper, wrapper,
      _this = this;
    this.io.emit('user_story_for_estimation', {
      id: id
    });
    wrapper = $('<div id="voting-header" class="component"></div>');
    wrapper.append(this.getUsItem(this.data[id]));
    wrapper.append($('<br>'));
    inputConfirm = $('<input id="voting-input">');
    confirmBtn = $('<button id="voting-confirm">Confirm voting</button>');
    wrapper.append(inputConfirm);
    wrapper.append(confirmBtn);
    confirmBtn.on('click', function() {
      if (inputConfirm.val() !== '') {
        _this.io.emit('user_story_estimation_end', {
          estimation: inputConfirm.val()
        });
      } else {
        console.log('cislo vole');
      }
    });
    votingInfoWrapper = $('<div id="voting-info"></div>');
    wrapper.append(votingInfoWrapper);
    j3r.changeContent(this.elements.content, wrapper);
  };

  Us.prototype.addVote = function(data) {
    var voteInfo;
    voteInfo = $('<div class="vote-info">' + data.user + ': <strong>' + data.value + '</strong></div>');
    this.elements.content.append(voteInfo);
  };

  return Us;

})();
