// Generated by CoffeeScript 1.6.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

j3r.Us = (function() {
  function Us(io, elements, data) {
    this.io = io;
    this.elements = elements;
    this.data = data;
    this.startVoting = __bind(this.startVoting, this);
  }

  Us.prototype.getUsList = function() {
    var itemData, liEl, ulEl, usEl, _i, _len, _ref;
    usEl = $('<div id="list-choose-us"></div>');
    if (this.data.length > 0) {
      ulEl = $('<ul></ul>');
      _ref = this.data;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        itemData = _ref[_i];
        liEl = $('<li></li>');
        liEl.append(this.getUsItem(itemData));
        ulEl.append(liEl);
      }
      usEl.append(ulEl);
    } else {
      usEl.append($('<div id="msg-info">no work. go and fuck yourself</div>'));
    }
    return usEl;
  };

  Us.prototype.getUsItem = function(itemData) {
    var usItem;
    return usItem = $('<div class="us-item" data-us-item-id="' + itemData.id + '"><span class="us-item-title">\
          ' + itemData.title + '</span><br>' + itemData.description + '</div>');
  };

  Us.prototype.startVoting = function(id) {
    var confirmBtn, inputConfirm, wrapper,
      _this = this;
    this.io.emit('user_story_for_estimation', {
      id: this.item.id
    });
    wrapper = $('<div id="voting-header"></div>');
    wrapper.append(this.item.getUsItem(id, this.data[id]));
    inputConfirm = $('<input id="voting-input">');
    confirmBtn = $('<button id="voting-confirm">Confirm voting</button>');
    wrapper.append(inputConfirm);
    wrapper.append(confirmBtn);
    confirmBtn.on('click', function() {
      if (inputConfirm.val() !== '') {
        return _this.io.emit('user_story_estimation_end', {
          estimation: inputConfirm.val()
        });
      } else {
        return console.log('cislo vole');
      }
    });
    wrapper.apend($('<div id="voting-info"></div>'));
    j3r.changeContent(this.elements.content, wrapper);
  };

  Us.prototype.addVote = function(data) {
    var voteInfo;
    voteInfo = $('<div class="vote-info">' + data.user + ': <strong>' + id.value + '</strong></div>');
    this.elements.content.append(voteInfo);
  };

  return Us;

})();
