// Generated by CoffeeScript 1.6.3
j3r.User = (function() {
  function User(io, elements) {
    this.io = io;
    this.elements = elements;
    this._listenComunication();
  }

  User.prototype.logIn = function(userEmail) {
    this.userEmail = userEmail;
    j3r.changeContent(this.elements.content, 'loguju');
    this.io.emit('user_log', {
      mail: this.userEmail
    });
    this.io.on('user_log_reply', function(data) {
      if (data.logged) {
        this.chooseTeam(data.rooms);
      }
    });
  };

  User.prototype.logOut = function() {
    this.io.emit('user_logout', {
      mail: this.userEmail
    });
    unset(window.localStorage.ppUser);
  };

  User.prototype.renderChooseTeam = function(teams) {
    var liEl, team, teamsEl, ulEl;
    teamsEl = $('<div id="list-choose-teams"></div>');
    if (teams.length > 0) {
      ulEl = $('<ul></ul>');
      for (team in teams) {
        liEl = $('<li>' + team.title + '</li>');
        liEl.on('click', function() {
          this.chooseTeam(team.id);
        });
        ulEl.append(liEl);
      }
      teamsEl.append(ulEl);
    } else {
      teamsEl.append($('<div id="msg-info">you are in none of our fucking teams</div>'));
    }
    j3r.changeContent(j3r.App.elements.content, teamsEl);
  };

  User.prototype.chooseTeam = function(id) {
    this.io.emit('user_choose_team', {
      id: id
    });
  };

  User.prototype._listenComunication = function() {
    this.io.on('user_enter_team', function(data) {
      this.userTeam = data.team;
      if (data.role = 'sm') {
        this.user = new j3r.SmUser(this.io, this.elements);
      } else if (data.role = 'monkey') {
        this.user = new j3r.MonkeyUser(this.io, this.elements);
      } else {
        console.log('whoopsie...wrong role returned');
      }
    });
  };

  return User;

})();

j3r.SmUser = (function() {
  function SmUser() {}

  SmUser.prototype.construct = function(io, elements) {
    this.io = io;
    this.elements = elements;
    _listenComunication();
    this.io.emit('fetch_user_stories');
  };

  SmUser.prototype._listenComunication = function() {
    this.io.on('user_stories_list', function(data) {
      var list;
      this.us = new j3r.Us(this.io, data);
      list = this.us.getUsList();
      return list.next('li').on('click', function() {
        var selectedUsId;
        selectedUsId = this.next('.us-item').attr('data-us-item-id');
        this.us.startVoting(selectedUsId);
      });
    });
    this.io.on('user_story_estimated', function(data) {
      this.us.addVote(data);
    });
    this.io.on('show-estimation', function(data) {
      this.io.emit('fetch_user_stories');
    });
  };

  return SmUser;

})();

j3r.MonkeyUser = (function() {
  function MonkeyUser() {}

  MonkeyUser.prototype.construct = function(io, elements) {
    this.io = io;
    this.elements = elements;
    return _listenComunication();
  };

  MonkeyUser.prototype._listenComunication = function() {};

  return MonkeyUser;

})();
